name: Publish

on:
  push:
    branches:
      - main
      - gpu

env:
  DOCKER_REGISTRY: docker.io
  DOCKER_IMAGE_NAME: sz-rust-ml
#  DOCKER_IMAGE_TAG: ${{ env.GITHUB_SHA }}

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_REGISTR_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

      - name: Build Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_REGISTR_USERNAME }}/${{env.DOCKER_IMAGE_NAME}}:latest,${{ secrets.DOCKER_REGISTR_USERNAME }}/${{env.DOCKER_IMAGE_NAME}}:${{ github.sha }}
          username: ${{ secrets.DOCKER_REGISTR_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
